name: shortnerwf
on: push #specify on what action the wf triggers. eg push/pull request/ release etc. to specify multiple use []
jobs:
    job1:
      name: First job
      runs-on: ubuntu-latest #specify which OS the job has to run. Github provides this OS platform
      steps:
        - name: Step one
          uses: action/checkout@v2 # this is an action provided by github to checkout the code
        - name: Step two
          run: env | sort #provide environment variable to the bash where command is going to get executed, and sort the output alphabetically
    job2:
      name: Second Job
      runs-on: windows-latest
      steps:
        - name: Step one
          uses: actions/checkout@v2
        - name: Step two
          run: "Get-ChildItem Env: | Sort-Object Name"
